### ISSUE TITLE
Windows 7 - beefy game.js fails

### ISSUE THREAD

**Issue by PranayPant** [kevinsimper/craftyjs-npm-example#1]
I cloned your repo and ran `npm install` and then `npm start`.

This is the error log:

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\Program Files\nodejs\\node.exe',
> 1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
> 1 verbose cli   'start' ]
> 2 info using npm@2.10.1
> 3 info using node@v0.12.4
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info prestart craftyjs-npm-example@1.0.0
> 6 info start craftyjs-npm-example@1.0.0
> 7 verbose unsafe-perm in lifecycle true
> 8 info craftyjs-npm-example@1.0.0 Failed to exec start script
> 9 verbose stack Error: craftyjs-npm-example@1.0.0 start: `beefy game.js`
> 9 verbose stack Exit status 1
> 9 verbose stack     at EventEmitter.<anonymous> (C:\Program >Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
> 9 verbose stack     at EventEmitter.emit (events.js:110:17)
> 9 verbose stack     at ChildProcess.<anonymous> (C:\Program >Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
> 9 verbose stack     at ChildProcess.emit (events.js:110:17)
> 9 verbose stack     at maybeClose (child_process.js:1015:16)
> 9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
> 10 verbose pkgid craftyjs-npm-example@1.0.0
> 11 verbose cwd C:\Users\Pranay\Desktop\Apps\Node.js\demos\craftyjs-npm-example
> 12 error Windows_NT 6.1.7601
> 13 error argv "C:\Program Files\nodejs\\node.exe" "C:\Program >Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
> 14 error node v0.12.4
> 15 error npm  v2.10.1
> 16 error code ELIFECYCLE
> 17 error craftyjs-npm-example@1.0.0 start: `beefy game.js`
> 17 error Exit status 1
> 18 error Failed at the craftyjs-npm-example@1.0.0 start script 'beefy game.js'.
> 18 error This is most likely a problem with the craftyjs-npm-example package,
> 18 error not with npm itself.
> 18 error Tell the author that this fails on your system:
> 18 error     beefy game.js
> 18 error You can get their info via:
> 18 error     npm owner ls craftyjs-npm-example
> 18 error There is likely additional logging output above.
> 19 verbose exit [ 1, true ]

**Comment by kevinsimper** [comment]
It seems that I forgot to add that you have to have browserify installed globally, I must have had it already when i made this.

npm install -g browserify

Can you try that and then do it again?

**Comment by kevinsimper** [comment]
Closing, but if you still have the issue, just write here!
